// 自動生成ファイル（scripts/update.mjs が週1で更新）。手動編集しないこと。
window.MOVIE_DATA = {
  "theater": "109シネマズ二子玉川",
  "theaterUrl": "https://109cinemas.net/futakotamagawa/",
  "updated": "2026-08-20T21:25:31.049Z",
  "count": 66,
  "movies": [
    {
      "id": "5583",
      "t": "新感染 ファイナル・エクスプレス 4K",
      "date": "2026-08-21",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTIvMTVfNDNfNTZfMzY0XzIyNzEzMl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227132_screenShots.jpg",
      "actor": "コン・ユ／マ・ドンソク／チョン・ユミ／キム・スアン／チェ・ウシク／シム・ウンギョン ほか",
      "director": "ヨン・サンホ",
      "env": "",
      "site": "https://109cinemas.net/movies/5583.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5587",
      "t": "ドラマなふたり",
      "date": "2026-08-21",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTgvMTFfMDZfNDNfOThfMjI1Mjc2X3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/225276_screenShots.jpg",
      "actor": "ゼンデイヤ／ロバート・パティンソン／アラナ・ハイム／ママドゥ・アティエ／ヘイリー・ゲイツ／ゾーイ・ウィンターズ／シドニー・レモン／マイケル・アボット・Jr ほか",
      "director": "クリストファー・ボルグリ",
      "env": "",
      "site": "https://109cinemas.net/movies/5587.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5633",
      "t": "劇場版　魔法少女まどか☆マギカ　［新編］ 叛逆の物語",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDIvMTBfNTFfMzlfMzY4XzE0MzI2X3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/14326_thumbnails.jpg",
      "actor": "【声の出演】悠木碧／斎藤千和／水橋かおり／喜多村英梨／野中藍／加藤英美里／阿澄佳奈 ほか",
      "director": "宮本幸裕",
      "env": "",
      "site": "https://109cinemas.net/movies/5633.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5548",
      "t": "オークストリートの異変",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTAvMjFfMDBfMTNfNTgxXzIyNDA3NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224074_screenShots.jpg",
      "actor": "ユアン・マクレガー／アン・ハサウェイ／メイジー・ステラ／クリスチャン・コンヴェリー【日本語吹き替え】森川智之／坂本真綾／早見沙織／木村皐誠／とにかく明るい安村 ほか",
      "director": "デヴィッド・ロバート・ミッチェル",
      "env": "IMAX,4DX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5548.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5579",
      "t": "レディ・オア・ノット 2",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDkvMTVfNDlfNTlfMzk1XzIyNzEyOF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227128_screenShots.jpg",
      "actor": "サマラ・ウィーヴィング／キャスリン・ニュートン／サラ・ミシェル・ゲラー／デヴィッド・クローネンバーグ／イライジャ・ウッド ほか",
      "director": "マット・ベティネッリ＝オルピン／タイラー・ジレット(レディオ・サイレンス)",
      "env": "",
      "site": "https://109cinemas.net/movies/5579.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5545",
      "t": "ブルーロック",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDcvMTZfNDlfMDRfNzI1XzIyMTE4Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/221186_screenShots.jpg",
      "actor": "⾼橋⽂哉／櫻井海⾳／⾼橋恭平／野村康太／⻘⽊柚／⻄垣匠／橘優輝／⽯川雷蔵／岩永丞威／浅野竣哉／櫻井佑樹／倉悠貴／東啓介／綱啓永／窪⽥正孝／K(＆TEAM)／樋口幸平／畑芽育／富本惣昭／木田佳介／三浦獠太／平山裕介／山時聡真／野間口徹／野波麻帆／春海四方 ほか",
      "director": "瀧悠輔",
      "env": "IMAX,4DX",
      "site": "https://109cinemas.net/movies/5545.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5546",
      "t": "ミニオンズ＆モンスターズ",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjQvMTdfNDZfMzRfNTY1XzIyMzcxMV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/223711_screenShots.jpg",
      "actor": "【声の出演】トレイ・パーカー／アリソン・ジャネイ／ジェシー・アイゼンバーグ／ジェフ・ブリッジス／ゾーイ・ドゥイッチ／ボビー・モイニハン／フィル・ラマール【日本語吹き替え版】松平健／千葉雄大／鈴木愛理／山寺宏一／バッテリィズ(エース／寺家)／LiSA／銀河万丈／寺依沙織／小野友樹／芹澤優 ほか",
      "director": "ピエール・コフィン",
      "env": "4DX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5546.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5547",
      "t": "あの星が降る丘で、君とまた出会いたい。",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMTlfMDhfMjY4XzIwNjU1OV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/206559_screenShots.jpg",
      "actor": "福原遥／細田佳央太／出口夏希／豊嶋花／井之脇海／伊藤健太郎／中嶋朋子／水上恒司／上川周作／小野塚勇人／松坂慶子／倍賞千恵子 ほか",
      "director": "新城 毅彦",
      "env": "",
      "site": "https://109cinemas.net/movies/5547.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5503",
      "t": "モアナと伝説の海",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMDcvMTJfMjlfNDBfNDE1XzIxNTA1M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/215053_screenShots.jpg",
      "actor": "キャサリン・ラガイア／ドウェイン・ジョンソン／レナ・オーウェン／ジョン・トゥイ／フランキー・アダムス【日本語吹き替え】TSUZUMI(ME:I)／尾上松也／キムラ緑子／福井晶一／真瀬はるか／ROLLY／倉田瑛茉 ほか",
      "director": "トーマス・ケイル",
      "env": "4DX",
      "site": "https://109cinemas.net/movies/5503.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5504",
      "t": "スパイダーマン：ブランド・ニュー・デイ",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMjBfNTJfNTM1XzE4NDM5M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/184393_screenShots.jpg",
      "actor": "トム・ホランド／ゼンデイヤ／セイディー・シンク／ジェイコブ・バタロン／ジョン・バーンサル／トラメル・ティルマン／マイケル・マンド／マーク・ラファロ ほか",
      "director": "デスティン・ダニエル・クレットン",
      "env": "IMAX,4DX-3D,SCREENX,ULTRA-4DX,Dolby-Atmos",
      "site": "https://109cinemas.net/movies/5504.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5505",
      "t": "映画クレヨンしんちゃん 奇々怪々！オラの妖怪バケ～ション",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMTVfMjZfMzQ2XzIxNzEzMV90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/217131_thumbnails.jpg",
      "actor": "【声の出演】小林由美子／ならはしみき／森川智之／こおろぎさとみ／伊藤沙莉／マユリカ(阪本／中谷)／梶裕貴／遠藤綾／下野紘／水瀬いのり／咲野俊介／小松未可子／佐藤せつじ／FRUITS ZIPPER(仲川瑠夏／早瀬ノエル) ほか",
      "director": "渡辺正樹",
      "env": "",
      "site": "https://109cinemas.net/movies/5505.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5538",
      "t": "開戦前夜",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMjRfMDlfNTcwXzIxNzkxNF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217914_screenShots.jpg",
      "actor": "池松壮亮／仲野太賀／岩田剛典／中村蒼／三浦貴大／二階堂ふみ／杉田雷麟／北村有起哉／嶋田久作／中野英雄／渡辺いっけい／別所哲也／松田龍平／奥田瑛二／國村隼／佐藤隆太／江口洋介／佐藤浩市 ほか",
      "director": "石井裕也",
      "env": "",
      "site": "https://109cinemas.net/movies/5538.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5499",
      "t": "映画ちいかわ 人魚の島のひみつ",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTAvMjFfMDJfMzlfNzUzXzIxNTQ5MV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/215491_screenShots.jpg",
      "actor": "【声の出演】青木遥／田中誠人／小澤亜李／井口裕香／淺井孝行／内田雄馬／島袋美由利／春海百乃／最上嗣生／鈴木みのり ほか",
      "director": "及川啓",
      "env": "",
      "site": "https://109cinemas.net/movies/5499.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "mubi": {
        "price": "一般 1,500円 / ジュニア 800円",
        "perk": "前売券1枚につきオリジナルA4クリアファイルをプレゼント（ちいかわ・ハチワレ・うさぎ・洞窟ver.の全4種／全国45万名限定）。豪華版ムビチケ（一般4,800円/ジュニア4,100円）はセイレーンおかおポシェット＆前髪クリップ2個付き。"
      },
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5500",
      "t": "パウ・パトロール ザ・ダイノ・ムービー",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTcvMTFfMjNfNTdfMzcwXzIxNDY2NV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/214665_screenShots.jpg",
      "actor": "【日本語吹き替え】潘めぐみ／石上静香／小市眞琴／井澤詩織／松田颯水／小堀幸／矢作紗友里／井料明里／魚建／大島優子／レインボー(ジャンボたかお／池田直人) ほか",
      "director": "カル・ブランカー",
      "env": "",
      "site": "https://109cinemas.net/movies/5500.html?t=futakotamagawa",
      "status": "now",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5502",
      "t": "映画『仮面ライダーゼッツ さよならのミッション』映画『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTQvMTJfMTBfNDJfMjY4XzIyNDI3N190aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/224277_thumbnails.jpg",
      "actor": "『仮面ライダーゼッツ さよならのミッション』今井竜太郎／古川雄輝／堀口真帆／三嶋健太／小貫莉奈／八木美樹／玉城裕規／小柳心／平川結月／曽野舜太／川平慈英／天野浩成／美村里江『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』長田光平／赤羽流河／角心菜／安井謙太郎／松永有紘／有坂心花／安田啓人／谷田ラナ／入山杏奈／平岡祐太／ジャルジャル(後藤淳平／福徳秀介)／高橋努 ほか",
      "director": "『仮面ライダーゼッツ さよならのミッション』上堀内佳寿也『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』福沢博文",
      "env": "",
      "site": "https://109cinemas.net/movies/5502.html?t=futakotamagawa",
      "status": "now",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5567",
      "t": "だぁれかさんとアソぼ？",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDIvMTJfMzhfMDVfMTA1XzIyNDA0OV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224049_screenShots.jpg",
      "actor": "鎮西寿々歌(FRUITS ZIPPER)／星乃あんな／大西利空／向井怜⾐／小國舞羽／室はんな／マキタスポーツ／オクイシュージ／菜葉菜／染谷準生／穂紫朋子／染谷将太 ほか",
      "director": "清水崇",
      "env": "",
      "site": "https://109cinemas.net/movies/5567.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5498",
      "t": "キングダム 魂の決戦",
      "date": "2026-07-17",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTcvMTFfMTdfNDlfMTI3XzIwNDc3Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/204776_screenShots.jpg",
      "actor": "山﨑賢人／吉沢亮／橋本環奈／清野菜名／満島真之介／岡山天音／志尊淳／神尾楓珠／結木滉星／三吉彩花／三山凌輝／山下美月／蒔田彩珠／山田裕貴／坂口憲二／豊川悦司／髙嶋政宏／要潤／加藤雅也／高橋光臣／平山祐介／一ノ瀬ワタル／佐久間由衣 ／勝矢／坂東彌十郎／橋本さとし／笹野高史／谷田歩／中村蒼／田中圭／斎藤工／玉木宏／佐藤浩市／小栗旬 ほか",
      "director": "佐藤信介",
      "env": "",
      "site": "https://109cinemas.net/movies/5498.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5486",
      "t": "トイ・ストーリー5",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjEvMTBfMDFfMzlfNzA5XzIwNzE2NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/207164_screenShots.jpg",
      "actor": "【声の出演】トム・ハンクス／ティム・アレン／ジョーン・キューザック／グレタ・リー／スカーレット・スピアーズ／コナン・オブライエン【日本語吹き替え】唐沢寿明／所ジョージ／日下由美／広瀬アリス／佐野勇斗／竜星涼／天野叶愛／白山乃愛／沢城みゆき／許綾香／落合弘治／三ツ矢雄二／三宅健太／遠藤純一／辻親八／松金よね子／戸田恵子／咲野俊介／森川智之／南真由／ふくまつ進紗／井上和(乃木坂46)／松井ケムリ(令和ロマン)／チョコレートプラネット(松尾駿／長田庄平) ほか",
      "director": "アンドリュー・スタントン／マッケナ・ハリス",
      "env": "",
      "site": "https://109cinemas.net/movies/5486.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5441",
      "t": "それいけ！アンパンマン パンタンと約束の星",
      "date": "2026-06-26",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDMvMTJfMzNfNTVfMjk4XzIxOTczNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219736_screenShots.jpg",
      "actor": "【声の出演】戸田恵子／中尾隆聖／土屋太鳳／EXIT(りんたろー。／兼近大樹)／津田健次郎 ほか",
      "director": "矢野博之",
      "env": "",
      "site": "https://109cinemas.net/movies/5441.html?t=futakotamagawa",
      "status": "now",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5431",
      "t": "Michael／マイケル",
      "date": "2026-06-12",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDMvMTJfMTdfNDNfMTM2XzE4MjQ2Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/182466_screenShots.jpg",
      "actor": "ジャファー・ジャクソン／ジュリアーノ・クルー・ヴァルディ／コールマン・ドミンゴ／ニア・ロング／ケンドリック・サンプソン／マイルズ・テラー／ローラ・ハリアー／ケイリン・デュレル・ジョーンズ ほか",
      "director": "アントワーン・フークア",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5431.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5669",
      "t": "＜ライブビューイング＞アイドリッシュセブン VISIBLIVE TOUR &quot;4WARD JOURNEY&quot;",
      "date": "2026-08-22",
      "img": "",
      "actor": "アイドリッシュセブン",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5669.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "4762",
      "t": "【1周年記念】大長編 タローマン 万博大爆発",
      "date": "2026-08-22",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjUvMDYvMDIvMTJfMjJfMDZfNDE4XzE5OTQwN190aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/199407_thumbnails.jpg",
      "actor": "タローマン／太陽の塔／地底の太陽／水差し男爵 ほか",
      "director": "藤井亮",
      "env": "",
      "site": "https://109cinemas.net/movies/4762.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5635",
      "t": "シェルター",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDIvMTZfMTZfNTJfOTk5XzIyNzgwOF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227808_screenShots.jpg",
      "actor": "ジェイソン・ステイサム／ボディ・レイ・ブレスナック／ビル・ナイ／ナオミ・アッキー／ハリエット・ウォルター／ダニエル・メイズ ほか",
      "director": "リック・ローマン・ウォー",
      "env": "",
      "site": "https://109cinemas.net/movies/5635.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5647",
      "t": "劇場版 TUBE 40th Anniversary Live ＆ Documentary ～40周年の航海記～",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDkvMTFfNDBfNDRfMjA0XzIzMDQ2NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/230464_screenShots.jpg",
      "actor": "TUBE(前田亘輝／春畑道哉／角野秀行／松本玲二)",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5647.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5660",
      "t": "ナイトボーン -夜哭-",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjMvMTRfMThfMzZfNjU1XzIxNDE4NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/214184_screenShots.jpg",
      "actor": "セイディ・ハーラ／ルパート・グリント ほか",
      "director": "ハンナ・ベルイホルム",
      "env": "",
      "site": "https://109cinemas.net/movies/5660.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5661",
      "t": "25周年記念 『ハリー・ポッターと賢者の石』",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjEvMTBfNTBfMjBfNTI5XzIyMTY3X3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/22167_thumbnails.jpg",
      "actor": "ダニエル・ラドクリフ／ルパート・グリント／エマ・ワトソン／リチャード・ハリス／マギー・スミス／アラン・リックマン／イアン・ハート／ロビー・コルトレーン／リチャード・グリフィス／フィオナ・ショウ／ジョン・クリーズ／トム・フェルトン／ハリー・メリング／ワーウィック・デイヴィス／ジョン・ハート／マシュー・ルイス／ジュリー・ウォルターズ／ボニー・ライト／デヴィッド・ブラッドリー／アルフィー・イーノック【日本語吹き替え】小野賢章／常盤祐貴／須藤祐実／永井一郎／谷育子／土師孝也／斎藤志郎／横堀悦夫／田村錦人／三枝享祐／上野容 ほか",
      "director": "クリス・コロンバス",
      "env": "IMAX-3D,4DX-3D",
      "site": "https://109cinemas.net/movies/5661.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5553",
      "t": "ラスト・サバイバー",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTcvMTdfMThfNDRfNzM2XzIyNTUxMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/225510_screenShots.jpg",
      "actor": "ジェイコブ・エロルディ／ジョシュ・ブローリン／マーガレット・クアリー／アリソン・ジャネイ／ガイ・ピアース【日本語吹き替え】武内駿輔／内田直哉／種崎敦美／井上和彦 ほか",
      "director": "リドリー・スコット",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5553.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5554",
      "t": "劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDEvMTFfMDNfMDdfOTk0XzE2MTY5NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/161694_screenShots.jpg",
      "actor": "【声の出演】悠木碧／斎藤千和／水橋かおり／喜多村英梨／野中藍／阿澄佳奈／加藤英美里 ほか",
      "director": "宮本幸裕",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5554.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5561",
      "t": "私はあなたを知らない、",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTZfNTdfNDNfODUxXzIyMDQ2N19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/220467_screenShots.jpg",
      "actor": "坂口健太郎／早瀬憩／倉田瑛茉／稲垣来泉／和田光沙／片山友希／畦田ひとみ／田牧そら／渡辺真起子／足立智充／黑田大輔／滝藤賢一／原田美枝子 ほか",
      "director": "中野量太",
      "env": "",
      "site": "https://109cinemas.net/movies/5561.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5566",
      "t": "時には懺悔を",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTZfNTlfMTFfNzg1XzE4NzgyNF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/187824_screenShots.jpg",
      "actor": "西島秀俊／満島ひかり／黒木華／宮藤官九郎／毎熊克哉／鈴木仁／烏森まど／山崎七海／唯野未歩子／野呂佳代／長井短／しんすけ／山下舜太／諸角優空／柴咲コウ／塚本晋也／片岡鶴太郎／佐藤二朗／役所広司 ほか",
      "director": "中島哲也",
      "env": "",
      "site": "https://109cinemas.net/movies/5566.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5714",
      "t": "KATY PERRY: THE LIFETIMES TOUR - LIVE FROM PARIS",
      "date": "2026-09-02",
      "img": "",
      "actor": "ケイティ・ペリー",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5714.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5636",
      "t": "バックルームズ",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDIvMTZfMjFfMTFfNTQ1XzIyOTA5M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/229093_screenShots.jpg",
      "actor": "キウェテル・イジョフォー／レナーテ・レインスヴェ／マーク・デュプラス／フィン・ベネット ほか",
      "director": "ケイン・パーソンズ",
      "env": "4DX,Dolby-Atmos",
      "site": "https://109cinemas.net/movies/5636.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5638",
      "t": "スワロウテイル 4Kリマスター",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDYvMTRfMzVfMTVfMzZfNzQzMF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/7430_thumbnails.jpg",
      "actor": "三上博史／Chara／伊藤歩／江口洋介／アンディ・ホイ／渡部篤郎／山口智子／大塚寧々／桃井かおり ほか",
      "director": "岩井俊二",
      "env": "",
      "site": "https://109cinemas.net/movies/5638.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5614",
      "t": "白鳥とコウモリ",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDYvMTBfMzdfMThfNDY2XzIxOTg5OF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219898_screenShots.jpg",
      "actor": "松村北斗／今田美桜／柄本佑／前原滉／井之脇海／宇野祥平／松岡依都美／松尾諭／丸山智己／三浦誠己／斉藤陽一郎／原田琥之佑／のせりん／漆山拓実／五頭岳夫／中村芝翫／井川遥／吉田羊／風吹ジュン／三浦友和 ほか",
      "director": "岸善幸",
      "env": "",
      "site": "https://109cinemas.net/movies/5614.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5626",
      "t": "べべフィン・ザ・ムービー：うたとまほうのピンキッツワールド",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMzFfNDlfNjExXzIyNTUwMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/225500_screenShots.jpg",
      "actor": "【声の出演】【日本語吹き替え】新垣杏菜／杉山はな／椿ナタニエル／久保田伶奈／三浦千幸／ケンドーコバヤシ／かなで(3時のヒロイン) ほか",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5626.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5627",
      "t": "獣兵衛忍風帖",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTdfMTRfMDlfOTU1X2p5dWJlX3Bvc3Rlcl80Sy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/jyube_poster_4K.jpg",
      "actor": "山寺宏一／篠原恵美／青野武／郷里大輔／関俊彦 ほか",
      "director": "川尻善昭",
      "env": "",
      "site": "https://109cinemas.net/movies/5627.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5639",
      "t": "映画「宇宙なんちゃら こてつくん」うっかり出てきた宇宙人を探せ！",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjMvMTRfMjFfMjFfNDA4XzIzMDE5N19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/230197_screenShots.jpg",
      "actor": "【声の出演】藤原夏海／榎木淳弥／玉木雅士／竹達彩奈／山口茜／山口勝平／青山穣／小山剛志／西健亮／杉田智和／ムロツヨシ ほか",
      "director": "筒井芳典",
      "env": "",
      "site": "https://109cinemas.net/movies/5639.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5674",
      "t": "オデュッセイア",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMDVfMTRfNjg0XzIwNDc3OF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/204778_screenShots.jpg",
      "actor": "マット・デイモン／トム・ホランド／アン・ハサウェイ／ロバート・パティンソン／ルピタ・ニョンゴ／ゼンデイヤ／シャーリーズ・セロン【日本語吹き替え】平田広明／榎木淳弥／坂本真綾／江口拓也／水樹奈々／白石涼子／本田貴子／内田雄馬／坂詰貴之／武内駿輔 ほか",
      "director": "クリストファー・ノーラン",
      "env": "IMAX,35mm-Film",
      "site": "https://109cinemas.net/movies/5674.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5616",
      "t": "ルックバック",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMjAvMTZfNDBfNTFfOTFfMjE4MDQwX3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/218040_screenShots.jpg",
      "actor": "出口夏希／蒔田彩珠／七瀬ふうり／岡田六花／野呂佳代／池田良／佐々木みゆ／山田真歩／宮藤官九郎／菅田将暉 ほか",
      "director": "是枝裕和",
      "env": "",
      "site": "https://109cinemas.net/movies/5616.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5617",
      "t": "最終楽章 響け！ユーフォニアム　後編",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMDRfMThfMzg5XzIyNjA5Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/226096_screenShots.jpg",
      "actor": "【声の出演】黒沢ともよ／朝井彩加／豊田萌絵／安済知佳／戸松遥／石谷春貴／大橋彩香／雨宮天／七瀬彩夏／久野美咲／土屋神葉／杉浦しおり／夏川椎菜／松田彩音／寺澤百花／陶山恵実里／櫻井孝宏／藤村鼓乃美／山岡ゆり／種﨑敦美／東山奈央／茅原実里／寿美菜子 ほか",
      "director": "小川太一",
      "env": "",
      "site": "https://109cinemas.net/movies/5617.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5618",
      "t": "5秒で完全犯罪を生成する方法",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjMvMTRfMjZfNTlfMzIwXzIyMjQ1OV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/222459_screenShots.jpg",
      "actor": "重岡大毅／原菜乃華／田中みな実／伊藤歩／黒田大輔／森岡龍／九十九黄助／石丸幹二 ほか",
      "director": "近藤亮太",
      "env": "",
      "site": "https://109cinemas.net/movies/5618.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5641",
      "t": "八つ墓村",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTAvMTRfNDNfMjRfOV8yMTk4OTVfc2NyZWVuU2hvdHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/219895_screenShots.jpg",
      "actor": "尾上松也／奥智哉／堀田真由／佐野岳／小野塚勇人／永瀬莉子／中村莟玉／笹野鈴々音／小籔千豊／中島亜梨沙／川瀬陽太／今野浩喜／渋川清彦／髙嶋政伸／高島礼子／滝藤賢一 ほか",
      "director": "清水崇",
      "env": "",
      "site": "https://109cinemas.net/movies/5641.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5657",
      "t": "ワンオペレーション",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTNfNTdfNTNfNDE4XzIzMTEzN19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/231137_screenShots.jpg",
      "actor": "ローズ・バーン／コナン・オブライエン／エイサップ・ロッキー／ダニエル・マクドナルド ほか",
      "director": "メアリー・ブロンスタイン",
      "env": "",
      "site": "https://109cinemas.net/movies/5657.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5619",
      "t": "踊る大捜査線 N.E.W. メトロポリスを駆け抜けろ！",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMjEvMTBfMzlfNTdfMzA5XzE4NjM1N190aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/186357_thumbnails.jpg",
      "actor": "織田裕二／趣里／白洲迅／佐々木蔵之介／増田貴久／野呂佳代／玉井詩織(ももいろクローバーZ)／藤吉夏鈴(櫻坂46)／齊藤なぎさ／佐藤二朗／ユースケ・サンタマリア／真矢ミキ／水野美紀／甲本雅裕／寺島進／伊藤淳史／滝藤賢一／松重豊／松下洸平／斉藤暁／小野武彦／北村総一朗／立木文彦／津田健次郎／関智一／野島健児 ほか",
      "director": "本広克行  ",
      "env": "",
      "site": "https://109cinemas.net/movies/5619.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5620",
      "t": "映画名探偵プリキュア！不思議な庭と2人の秘密",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMDlfNTBfMTg5XzIyNDU2Ml9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224562_screenShots.jpg",
      "actor": "【声の出演】千賀光莉／本渡楓／東山奈央／松岡美⾥／髙橋ミナミ／⾼森奈津美／南條愛乃／花井美春／⻑縄まりあ／種﨑敦美／松⽥颯⽔／上⽥麗奈／加藤英美⾥／⽺宮妃那／梶裕貴 ほか",
      "director": "上⽥華⼦",
      "env": "",
      "site": "https://109cinemas.net/movies/5620.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5625",
      "t": "アベンジャーズ／エンドゲーム：アンコール",
      "date": "2026-09-23",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMzBfMTlfNTUxXzY5MDg5X3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/69089_screenShots.jpg",
      "actor": "ロバート･ダウニー Jr.／クリス・エヴァンス／マーク・ラファロ／クリス・ヘムズワース／スカーレット・ヨハンソン／ジェレミー・レナー／ドン・チードル／ポール・ラッド／ブリー・ラーソン／カレン・ギラン／ダナイ・グリラ／ベネディクト・ウォン／ジョン・ファヴロー／ブラッドリー・クーパー／グウィネス･パルトロウ／ジョシュ・ブローリン【日本語吹き替え】藤原啓治／中村悠一／宮内敦士／三宅健太 ほか",
      "director": "アンソニー・ルッソ／ジョー・ルッソ",
      "env": "",
      "site": "https://109cinemas.net/movies/5625.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5643",
      "t": "マッチング TRUE LOVE",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTcvMTdfMjFfMTNfODk1XzIxNjYxMV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/216611_screenShots.jpg",
      "actor": "土屋太鳳／佐久間大介(Snow Man)／クァク・ドンヨン／豊嶋花／倉悠貴／根矢涼香／冨手麻妙／塚田僚一／瀧七海／濱正悟／加藤史帆／花瀬琴音／伊島空／後藤剛範／真飛聖 ほか",
      "director": "内田英治",
      "env": "",
      "site": "https://109cinemas.net/movies/5643.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5672",
      "t": "襲名",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMDJfMDVfMTA4XzIyNzI2MF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227260_screenShots.jpg",
      "actor": "市川團十郎／市川新之助【ナレーション】杏 ほか",
      "director": "三池崇史",
      "env": "",
      "site": "https://109cinemas.net/movies/5672.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5622",
      "t": "ハート・オブ・ビースト",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMjFfNThfNDA0XzIyOTE4MV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/229181_screenShots.jpg",
      "actor": "ブラッド・ピット／J・K・シモンズ／アンナ・ラム ほか",
      "director": "デヴィッド・エアー",
      "env": "",
      "site": "https://109cinemas.net/movies/5622.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5623",
      "t": "藁にもすがる獣たち",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMjRfMTVfMjA2XzIyNDQxMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224410_screenShots.jpg",
      "actor": "鈴鹿央士／成宮寛貴／森七菜／MEGUMI／前田旺志郎／二ノ宮隆太郎／青木マッチョ／岩松了／小手伸也／風吹ジュン ほか",
      "director": "城定秀夫",
      "env": "",
      "site": "https://109cinemas.net/movies/5623.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5624",
      "t": "シネマ歌舞伎　ふるあめりかに袖はぬらさじ",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMjdfMjNfNzI5XzE3NzczX3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/17773_thumbnails.jpg",
      "actor": "坂東玉三郎／中村獅童／中村七之助／中村福助／市川海老蔵／坂東三津五郎／中村勘三郎　ほか",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5624.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5675",
      "t": "ディスクロージャー・デイ",
      "date": "2026-10-01",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMjNfMzFfODk2XzIxNzQxNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217416_screenShots.jpg",
      "actor": "エミリー・ブラント／ジョシュ・オコナー／コリン・ファース／イヴ・ヒューソン／コールマン・ドミンゴ ほか",
      "director": "スティーブン・スピルバーグ",
      "env": "",
      "site": "https://109cinemas.net/movies/5675.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5676",
      "t": "ママがもうこの世界にいなくても　私の命の日記",
      "date": "2026-10-02",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTAvMTRfMjJfNDNfMzQ0XzIyNTMxMl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/225312_screenShots.jpg",
      "actor": "川口春奈／高杉真宙／松本穂香／中島瑠菜／デビット伊東／小林聡美／清水くるみ／笠原秀幸／豊本明長／一ノ瀬颯／星野真里／森田望智 ほか",
      "director": "山戸結希",
      "env": "",
      "site": "https://109cinemas.net/movies/5676.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5677",
      "t": "ファーストボイス ー私たちの逆転裁判ー",
      "date": "2026-10-02",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTcvMTFfMDdfMjNfMTI4XzIyODQzNF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/228434_thumbnails.jpg",
      "actor": "綾瀬はるか／ファーストサマーウイカ／松本穂香／峯村リエ／山田真歩／工藤阿須加／水川かたまり(空気階段)／鈴鹿央士／迫田孝也／酒向芳／木村多江／筒井道隆 ほか",
      "director": "前田哲",
      "env": "",
      "site": "https://109cinemas.net/movies/5677.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5716",
      "t": "時給三〇〇円の死神",
      "date": "2026-10-02",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTcvMTFfMTZfMjhfNjc1XzIxOTMzMF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/219330_thumbnails.jpg",
      "actor": "西畑大吾／福本莉子／渋谷凪咲／齋藤潤／泉谷星奈／佐津川愛美／山口馬木也／小澤征悦 ほか",
      "director": "酒井麻衣",
      "env": "",
      "site": "https://109cinemas.net/movies/5716.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5680",
      "t": "DIGGER／ディガー",
      "date": "2026-10-09",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMzBfNTBfNjI4XzIxNzQyMl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217422_screenShots.jpg",
      "actor": "トム・クルーズ／リズ・アーメッド／ジョン・グッドマン／ザンドラ・ヒュラー／ジェシー・プレモンス／マイケル・スタールバーグ ほか",
      "director": "アレハンドロ・G・イニャリトゥ",
      "env": "",
      "site": "https://109cinemas.net/movies/5680.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5681",
      "t": "汝、星のごとく",
      "date": "2026-10-09",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMDUvMTZfMjlfMTRfNTY1XzIwNDE3NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/204174_screenShots.jpg",
      "actor": "横浜流星／広瀬すず／松村北斗／中村アン／濱田岳／尾野真千子／木村佳乃／石田ゆり子／長谷川博己 ほか",
      "director": "藤井道人",
      "env": "",
      "site": "https://109cinemas.net/movies/5681.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5682",
      "t": "バイオハザード",
      "date": "2026-10-09",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMzBfNTJfMTU3XzIyNjM3M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/226373_screenShots.jpg",
      "actor": "オースティン・エイブラムス／ザック・チェリー／カーリー・レイス／ポール・ウォルター・ハウザー ほか",
      "director": "ザック・クレッガー",
      "env": "",
      "site": "https://109cinemas.net/movies/5682.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5684",
      "t": "ガールズ＆パンツァー 最終章 第5話",
      "date": "2026-10-09",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfMzhfMjFfNjU1XzIxNDk1OF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/214958_thumbnails.jpg",
      "actor": "【声の出演】渕上舞／茅野愛衣／尾崎真実／中上育実／井口裕香／原由実／津田美波／安済知佳 ほか",
      "director": "水島努",
      "env": "",
      "site": "https://109cinemas.net/movies/5684.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5685",
      "t": "ストリートファイター／ザ・ムービー",
      "date": "2026-10-16",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfNDBfMjNfNjMzXzIyMjU0Ml90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/222542_thumbnails.jpg",
      "actor": "ノア・センティネオ／アンドリュー・小路／カリーナ・リャン／ジョー・“ロマン・レインズ”・アノアイ／デヴィッド・ダストマルチャン／コーディ・ローデス／アンドリュー・シュルツ／ヴィドゥユト・ジャームワール／エリック・アンドレ／オーヴィル・ペック／オリヴィエ・リヒタース／後藤洋央紀／ライナ・バランディンガム／アレクサンダー・ヴォルカノフスキー／カイル・ムーニー／メル・ジャーンソン／With カーティス・“50セント”・ジャクソン／ジェイソン・モモア【日本語吹き替え】高橋広樹／岸祐二／折笠富美子／安元洋貴／沢城みゆき／鶴岡聡／チョー ほか",
      "director": "キタオ・サクライ",
      "env": "",
      "site": "https://109cinemas.net/movies/5685.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5689",
      "t": "劇場アニメ「青春ブタ野郎はディアフレンドの夢を見ない」",
      "date": "2026-10-16",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfNDJfMDlfOF8yMTcxMzNfc2NyZWVuU2hvdHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/217133_screenShots.jpg",
      "actor": "【声の出演】⽯川界⼈／瀬⼾⿇沙美／⾬宮天／⼭根綺／⼩原好美／⽯⾒舞菜⾹／上⽥麗奈／東⼭奈央／種﨑敦美／内⽥真礼／久保ユリカ／⽔瀬いのり ほか",
      "director": "増井壮一",
      "env": "",
      "site": "https://109cinemas.net/movies/5689.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5717",
      "t": "BanG Dream! Ave Mujica prima aurora",
      "date": "2026-10-16",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTgvMTdfNTJfNTdfMTUxX05PVkFfT1ZBX0tWMl90MV9ub3VoaW4ucG5nIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/NOVA_OVA_KV2_t1_nouhin.png",
      "actor": "【声の出演】佐々木李子／渡瀬結月／岡田夢以／米澤茜／高尾奏音 ほか",
      "director": "柿本広大",
      "env": "",
      "site": "https://109cinemas.net/movies/5717.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5691",
      "t": "うるわしの宵の月",
      "date": "2026-10-23",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfNTRfMzNfODI0XzIxODAxNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/218016_screenShots.jpg",
      "actor": "道枝駿佑／安斉星来／水沢林太郎／星乃夢奈／鈴川紗由／大倉空人／阿佐辰美／与田祐希／藤木直人 ほか",
      "director": "竹村謙太郎",
      "env": "",
      "site": "https://109cinemas.net/movies/5691.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5694",
      "t": "野田版 桜の森の満開の下",
      "date": "2026-10-23",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMzEvMTRfNTdfNThfNDUxXzY3OTUxX3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/67951_screenShots.jpg",
      "actor": "中村勘九郎／松本幸四郎／中村七之助／中村梅枝／坂東巳之助／坂東新悟／中村児太郎／中村虎之介／市川青虎／中村芝のぶ／中村梅花／中村吉之丞／市川猿弥／片岡亀蔵／坂東彌十郎／中 扇雀 ほか",
      "director": "野田秀樹（作・演出）",
      "env": "",
      "site": "https://109cinemas.net/movies/5694.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5707",
      "t": "耳をすませば 4Kデジタルリマスター",
      "date": "2026-10-23",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTAvMTVfMTFfNThfOTQ0X3RRd1MxZHdJNzhHcC5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/tQwS1dwI78Gp.jpg",
      "actor": "【声の出演】本名陽子／高橋一生／小林桂樹／露口茂／立花隆／室井滋／山下容莉枝／佳山麻衣子／中島義実／飯塚雅弓／高山みなみ／岸部シロー／笛吹雅子／江川卓／中村晴彦 ほか",
      "director": "近藤喜文",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5707.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5708",
      "t": "借りぐらしのアリエッティ 4Kデジタルリマスター",
      "date": "2026-10-23",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDgvMTAvMTVfMTdfMTBfMzA3X3FwaDhJY01UckNFSi5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/qph8IcMTrCEJ.jpg",
      "actor": "声の出演：志田未来／神木隆之介／大竹しのぶ／竹下景子／藤原竜也／三浦友和／樹木希林／羽鳥慎一／吉野正弘　ほか",
      "director": "米林宏昌",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5708.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    }
  ]
};
