// 自動生成ファイル（scripts/update.mjs が週1で更新）。手動編集しないこと。
window.MOVIE_DATA = {
  "theater": "109シネマズ二子玉川",
  "theaterUrl": "https://109cinemas.net/futakotamagawa/",
  "updated": "2026-07-19T04:52:42.433Z",
  "count": 56,
  "movies": [
    {
      "id": "5498",
      "t": "キングダム 魂の決戦",
      "date": "2026-07-17",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMDcvMTJfMjBfMjhfNDE2XzIwNDc3Nl90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/204776_thumbnails.jpg",
      "actor": "山﨑賢人／吉沢亮／橋本環奈／清野菜名／満島真之介／岡山天音／志尊淳／神尾楓珠／結木滉星／三吉彩花／三山凌輝／山下美月／蒔田彩珠／山田裕貴／坂口憲二／豊川悦司／髙嶋政宏／要潤／加藤雅也／高橋光臣／平山祐介／一ノ瀬ワタル／佐久間由衣 ／勝矢／坂東彌十郎／橋本さとし／笹野高史／谷田歩／中村蒼／田中圭／斎藤工／玉木宏／佐藤浩市／小栗旬 ほか",
      "director": "佐藤信介",
      "env": "IMAX,4DX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5498.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5542",
      "t": "君と花火と約束と",
      "date": "2026-07-17",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjgvMTVfMjdfMzFfOTIyXzIxOTg5N19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219897_screenShots.jpg",
      "actor": "【声の出演】佐藤勝利(timelesz)／ 原菜乃華／高橋李依／横澤夏子 ほか",
      "director": "鈴木慧",
      "env": "",
      "site": "https://109cinemas.net/movies/5542.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5571",
      "t": "オブセッション　災愛",
      "date": "2026-07-17",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDMvMDlfNTNfNDRfMzQ2XzIyODM5M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/228393_screenShots.jpg",
      "actor": "マイケル・ジョンストン／インディ・ナヴァレッテ／クーパー・トムリンソン／メーガン・ローレス ほか",
      "director": "カリー・バーカー",
      "env": "",
      "site": "https://109cinemas.net/movies/5571.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5526",
      "t": "ヌーヴェルヴァーグ",
      "date": "2026-07-10",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjUvMTJfMzdfNDFfMTg2XzIxOTgxOF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219818_screenShots.jpg",
      "actor": "ギヨーム・マルベック／ゾーイ・ドゥイッチ／オーブリー・デュラン ほか",
      "director": "リチャード・リンクレイター",
      "env": "",
      "site": "https://109cinemas.net/movies/5526.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5529",
      "t": "トロフィー",
      "date": "2026-07-10",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjUvMTJfNDJfNTBfNjMwXzIyMzc5NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/223794_screenShots.jpg",
      "actor": "恒那／ちすん／笠松将／市川実和子／井浦新 ほか",
      "director": "孫明雅",
      "env": "",
      "site": "https://109cinemas.net/movies/5529.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5530",
      "t": "ブリング・ハー・バック",
      "date": "2026-07-10",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjUvMTJfNDVfMzlfNzE2XzIyNDI4NV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224285_screenShots.jpg",
      "actor": "ビリー・バラット／ソラ・ウォン／サリー・ホーキンス／ジョナ・レン・フィリップス／スティーブン・フィリップス／ミーシャ・ヘイウッド／サリー＝アン・アプトン ほか",
      "director": "ダニーフィリッポウ／マイケル・フィリッポウ",
      "env": "",
      "site": "https://109cinemas.net/movies/5530.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5568",
      "t": "大統領のケーキ",
      "date": "2026-07-10",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDIvMTJfNDNfMjVfNTUyXzIyNDYzOV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224639_screenShots.jpg",
      "actor": "バニーン・アハマド・ナーイフ／サッジャード・モハンマド・カーセム／ワヒーダ・サーベト／ラヒーム・アルハジ ほか",
      "director": "ハサン・ハーディ",
      "env": "",
      "site": "https://109cinemas.net/movies/5568.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5486",
      "t": "トイ・ストーリー5",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjEvMTBfMDFfMzlfNzA5XzIwNzE2NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/207164_screenShots.jpg",
      "actor": "【声の出演】トム・ハンクス／ティム・アレン／ジョーン・キューザック／グレタ・リー／スカーレット・スピアーズ／コナン・オブライエン【日本語吹き替え】唐沢寿明／所ジョージ／日下由美／広瀬アリス／佐野勇斗／竜星涼／天野叶愛／白山乃愛／沢城みゆき／許綾香／落合弘治／三ツ矢雄二／三宅健太／遠藤純一／辻親八／松金よね子／戸田恵子／咲野俊介／森川智之／南真由／ふくまつ進紗／井上和(乃木坂46)／松井ケムリ(令和ロマン)／チョコレートプラネット(松尾駿／長田庄平) ほか",
      "director": "アンドリュー・スタントン／マッケナ・ハリス",
      "env": "IMAX,4DX-3D,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5486.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5487",
      "t": "口に関するアンケート",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjEvMTBfMDJfNTFfOTgyXzIxNTUwNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/215506_screenShots.jpg",
      "actor": "板垣李光人／綱啓永／吉川愛／MOMONA(ME:I)／森愁斗／西山智樹(TAGRIGHT)／柄本時生／中村獅童 ほか",
      "director": "清水崇",
      "env": "",
      "site": "https://109cinemas.net/movies/5487.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5489",
      "t": "サヨナラの引力",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDgvMTBfNDZfMjJfNjQ3XzIyNDkwNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224906_screenShots.jpg",
      "actor": "ク・ギョファン／ムン・ガヨン／シン・ジョングン／イ・サンヨプ ほか",
      "director": "キム・ドヨン",
      "env": "",
      "site": "https://109cinemas.net/movies/5489.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5490",
      "t": "ラブ≠コメディ",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTgvMTVfMjFfMDRfMzA0XzIyMjAzMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/222030_screenShots.jpg",
      "actor": "中島健人／長濱ねる／板谷由夏／塩野瑛久／本多力／前野朋哉／今野浩喜／野村麻純／宮崎吐夢／磯山さやか／岩井拳士朗／信川清順／工藤美桜／今野大輝(B＆ZAI)／北代祐太／アパッチ長男／菊田竜大(ハナコ)／三石琴乃／光石研／財前直見 ほか",
      "director": "紙谷楓",
      "env": "",
      "site": "https://109cinemas.net/movies/5490.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5492",
      "t": "THE ORIGIN OF ULTRAMAN",
      "date": "2026-07-03",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMDcvMTJfMDRfNDlfODI0XzIyNTQwMF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/225400_thumbnails.jpg",
      "actor": "ギレルモ・デル・トロ／是枝裕和／小島秀夫／庵野秀明／樋口真嗣／ニコラス・ウィンディング・レフン／シャノン・ティンドル／ジョン・アオシマ／成田カイリ／パット・キャディガン／清水節／椹木野衣／岡田秀則／黒部進／桜井浩子／毒蝮三太夫／飯島敏宏／佐川和夫／鈴木清／飯塚定雄／宍倉徳子 ほか",
      "director": "中村裕／吉田一貴",
      "env": "",
      "site": "https://109cinemas.net/movies/5492.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5440",
      "t": "スーパーガール",
      "date": "2026-06-26",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDkvMDlfMjVfMzRfMzY5XzIxNzUyN19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217527_screenShots.jpg",
      "actor": "ミリー・オールコック／イヴ・リドリー／ジェイソン・モモア【日本語吹き替え】永瀬アンナ／武内駿輔 ほか",
      "director": "クレイグ・ギレスピー",
      "env": "IMAX,4DX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5440.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5441",
      "t": "それいけ！アンパンマン パンタンと約束の星",
      "date": "2026-06-26",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDMvMTJfMzNfNTVfMjk4XzIxOTczNl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219736_screenShots.jpg",
      "actor": "【声の出演】戸田恵子／中尾隆聖／土屋太鳳／EXIT(りんたろー。／兼近大樹)／津田健次郎 ほか",
      "director": "矢野博之",
      "env": "",
      "site": "https://109cinemas.net/movies/5441.html?t=futakotamagawa",
      "status": "now",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5442",
      "t": "新劇場版☆ケロロ軍曹 復活して速攻地球滅亡の危機であります！",
      "date": "2026-06-26",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMjMvMTJfMjJfMzNfNDgzXzIwNDE3M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/204173_screenShots.jpg",
      "actor": "【声の出演】渡辺久美子／小桜エツコ／中田譲治／子安武人／草尾毅／桑島法子／斎藤千和／平松晶子／池澤春菜／石田彰／広橋涼／能登麻美子／ジェシー(SixTONES)／あの／粗品(霜降り明星)／佐藤景瑚／八木勇征／スザンヌ／渡辺莉奈／関智一／花江夏樹／山寺宏一／山田孝之／木南晴夏／ムロツヨシ／佐藤二朗／宅麻伸／鈴木亮平／小栗旬／菅田将暉／橋本環奈／中村勘九郎／柳楽優弥／吉沢亮【ナレーション】長谷川忍(シソンヌ) ほか",
      "director": "【総監督】福田雄一【監督】追崎史敏",
      "env": "4DX",
      "site": "https://109cinemas.net/movies/5442.html?t=futakotamagawa",
      "status": "now",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5436",
      "t": "免許返納!?",
      "date": "2026-06-19",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjYvMTBfMDJfNDFfNDY1XzIxNzMzNV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217335_screenShots.jpg",
      "actor": "舘ひろし／西野七瀬／黒川想矢／河井青葉／伊能昌幸／佐藤五郎／泉谷星奈／斉藤暁／内藤剛志／ベンガル／大地真央／品川徹／西岡德馬／南野陽子／八嶋智人／中山忍／MEGUMI／真矢ミキ／吉田鋼太郎／宇崎竜童 ほか",
      "director": "河合勇人",
      "env": "",
      "site": "https://109cinemas.net/movies/5436.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5437",
      "t": "黒牢城",
      "date": "2026-06-19",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDkvMTJfMjJfMzdfNjgxXzIxOTU2MV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/219561_screenShots.jpg",
      "actor": "本木雅弘／菅田将暉／吉高由里子／青木崇高／宮舘涼太／柄本佑／ユースケ・サンタマリア／吉原光夫／坂東龍汰／荒川良々／渋川清彦／渡辺いっけい／オダギリジョー／近藤芳正／矢柴俊博／木原勝利／河内大和／吉岡睦雄／上川周作／前田旺志郎／坂東新悟 ほか",
      "director": "黒沢清",
      "env": "",
      "site": "https://109cinemas.net/movies/5437.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5438",
      "t": "急に具合が悪くなる",
      "date": "2026-06-19",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDMvMTJfMjdfMTZfNzU3XzIwMDI0Ml9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/200242_screenShots.jpg",
      "actor": "ヴィルジニー・エフィラ／岡本多緒／長塚京三／⿊崎煌代 ほか",
      "director": "濱口竜介",
      "env": "",
      "site": "https://109cinemas.net/movies/5438.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5431",
      "t": "Michael／マイケル",
      "date": "2026-06-12",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDQvMDMvMTJfMTdfNDNfMTM2XzE4MjQ2Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/182466_screenShots.jpg",
      "actor": "ジャファー・ジャクソン／ジュリアーノ・クルー・ヴァルディ／コールマン・ドミンゴ／ニア・ロング／ケンドリック・サンプソン／マイルズ・テラー／ローラ・ハリアー／ケイリン・デュレル・ジョーンズ ほか",
      "director": "アントワーン・フークア",
      "env": "IMAX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5431.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5347",
      "t": "スター・ウォーズ／マンダロリアン・アンド・グローグー",
      "date": "2026-05-22",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMTQvMTJfMzNfNDNfMTA2XzE5OTQyMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/199420_screenShots.jpg",
      "actor": "ペドロ・パスカル／シガニー・ウィーバー ほか",
      "director": "ジョン・ファブロー",
      "env": "4DX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5347.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5341",
      "t": "プラダを着た悪魔２",
      "date": "2026-05-01",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDMvMDIvMTFfNDZfMDFfODQ1XzIxNDc4NV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/214785_screenShots.jpg",
      "actor": "メリル・ストリープ／アン・ハサウェイ／エミリー・ブラント／スタンリー・トゥッチ／トレイシー・トムズ／ティボー・フェルドマン／ケネス・ブラナー／シモーヌ・アシュリー／ジャスティン・セロー／ルーシー・リュー／パトリック・ブラモール／ケイレブ・ヒーロン／ヘレン・J・シェン／ポーリーン・シャラメ／B・J・ノヴァク／コンラッド・リカモラ ほか",
      "director": "デヴィッド・フランケル",
      "env": "",
      "site": "https://109cinemas.net/movies/5341.html?t=futakotamagawa",
      "status": "now",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5250",
      "t": "ザ・スーパーマリオギャラクシー・ムービー",
      "date": "2026-04-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDIvMDUvMTFfMjlfMTZfNDEwXzIxNDc3Ml9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/214772_screenShots.jpg",
      "actor": "【声の出演】クリス・プラット／アニャ・テイラー＝ジョイ／チャーリー・デイ／ジャック・ブラック／キーガン＝マイケル・キー／ケヴィン・マイケル・リチャードソン【日本語吹き替え版】宮野真守／志田有彩／畠中祐／三宅健太／関智一／坂本真綾／山下大輝 ほか",
      "director": "アーロン・ホーヴァス／マイケル・ジェレニック",
      "env": "4DX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5250.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5251",
      "t": "名探偵コナン ハイウェイの堕天使",
      "date": "2026-04-10",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDIvMTIvMTFfMDdfNDZfNTMyXzIwNzg3MF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/207870_screenShots.jpg",
      "actor": "【声の出演】高山みなみ／山崎和佳奈／小山力也／沢城みゆき／三木眞一郎／神奈延年／横浜流星／畑芽育 ほか\r\n\r\n　　　　　",
      "director": "蓮井隆弘",
      "env": "",
      "site": "https://109cinemas.net/movies/5251.html?t=futakotamagawa",
      "status": "now",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5499",
      "t": "映画ちいかわ 人魚の島のひみつ",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTAvMjFfMDJfMzlfNzUzXzIxNTQ5MV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/215491_screenShots.jpg",
      "actor": "【声の出演】青木遥／田中誠人／小澤亜李／井口裕香／淺井孝行／内田雄馬／島袋美由利／春海百乃／最上嗣生／鈴木みのり ほか",
      "director": "及川啓",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5499.html?t=futakotamagawa",
      "status": "soon",
      "cat": "fam",
      "mubi": {
        "price": "一般 1,500円 / ジュニア 800円",
        "perk": "前売券1枚につきオリジナルA4クリアファイルをプレゼント（ちいかわ・ハチワレ・うさぎ・洞窟ver.の全4種／全国45万名限定）。豪華版ムビチケ（一般4,800円/ジュニア4,100円）はセイレーンおかおポシェット＆前髪クリップ2個付き。"
      },
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5500",
      "t": "パウ・パトロール ザ・ダイノ・ムービー",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTcvMTFfMjNfNTdfMzcwXzIxNDY2NV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/214665_screenShots.jpg",
      "actor": "【日本語吹き替え】潘めぐみ／石上静香／小市眞琴／井澤詩織／松田颯水／小堀幸／矢作紗友里／井料明里／魚建／大島優子／レインボー(ジャンボたかお／池田直人) ほか",
      "director": "カル・ブランカー",
      "env": "",
      "site": "https://109cinemas.net/movies/5500.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5501",
      "t": "シネマ歌舞伎　新作歌舞伎『風の谷のナウシカ』後編",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMjEvMTBfMjNfMDdfNjA4Xzc5MzIwX3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/79320_screenShots.jpg",
      "actor": "尾上菊之助／中村七之助／尾上松也／中村歌昇 坂東巳之助／尾上右近／中村種之助／中村米吉／中村吉之丞／市村橘太郎／嵐橘三郎／片岡亀蔵／河原崎権十郎／市村萬次郎／中村錦之助／中村又五郎／中村歌六　ほか",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5501.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5502",
      "t": "映画『仮面ライダーゼッツ さよならのミッション』映画『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTQvMTJfMTBfNDJfMjY4XzIyNDI3N190aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/224277_thumbnails.jpg",
      "actor": "『仮面ライダーゼッツ さよならのミッション』今井竜太郎／古川雄輝／堀口真帆／三嶋健太／小貫莉奈／八木美樹／玉城裕規／小柳心／平川結月／曽野舜太／川平慈英／天野浩成／美村里江『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』長田光平／赤羽流河／角心菜／安井謙太郎／松永有紘／有坂心花／安田啓人／谷田ラナ／入山杏奈／平岡祐太／ジャルジャル(後藤淳平／福徳秀介)／高橋努 ほか",
      "director": "『仮面ライダーゼッツ さよならのミッション』上堀内佳寿也『超宇宙刑事ギャバン インフィニティ 太陽が泣いた日』福沢博文",
      "env": "",
      "site": "https://109cinemas.net/movies/5502.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5567",
      "t": "だぁれかさんとアソぼ？",
      "date": "2026-07-24",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDIvMTJfMzhfMDVfMTA1XzIyNDA0OV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224049_screenShots.jpg",
      "actor": "鎮西寿々歌(FRUITS ZIPPER)／星乃あんな／大西利空／向井怜⾐／小國舞羽／室はんな／マキタスポーツ／オクイシュージ／菜葉菜／染谷準生／穂紫朋子／染谷将太 ほか",
      "director": "清水崇",
      "env": "",
      "site": "https://109cinemas.net/movies/5567.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5576",
      "t": "『2026＆TEAM CONCERT TOUR &#39;BLAZE THE WAY&#39; in JAPAN』ライブビューイング",
      "date": "2026-07-26",
      "img": "",
      "actor": "＆TEAM",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5576.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5503",
      "t": "モアナと伝説の海",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDUvMDcvMTJfMjlfNDBfNDE1XzIxNTA1M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/215053_screenShots.jpg",
      "actor": "キャサリン・ラガイア／ドウェイン・ジョンソン【日本語吹き替え】TSUZUMI(ME:I)／尾上松也 ほか",
      "director": "トーマス・ケイル",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5503.html?t=futakotamagawa",
      "status": "soon",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5504",
      "t": "スパイダーマン：ブランド・ニュー・デイ",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMjBfNTJfNTM1XzE4NDM5M19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/184393_screenShots.jpg",
      "actor": "トム・ホランド／ゼンデイヤ／セイディー・シンク／ジェイコブ・バタロン／ジョン・バーンサル／トラメル・ティルマン／マイケル・マンド／マーク・ラファロ ほか",
      "director": "デスティン・ダニエル・クレットン",
      "env": "IMAX,4DX-3D,SCREENX,ULTRA-4DX,Dolby-Atmos",
      "site": "https://109cinemas.net/movies/5504.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5505",
      "t": "映画クレヨンしんちゃん 奇々怪々！オラの妖怪バケ～ション",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMTVfMjZfMzQ2XzIxNzEzMV90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/217131_thumbnails.jpg",
      "actor": "【声の出演】小林由美子／ならはしみき／森川智之／こおろぎさとみ／伊藤沙莉／マユリカ(阪本／中谷)／梶裕貴／遠藤綾／下野紘／水瀬いのり／咲野俊介／小松未可子／佐藤せつじ／FRUITS ZIPPER(仲川瑠夏／早瀬ノエル) ほか",
      "director": "渡辺正樹",
      "env": "",
      "site": "https://109cinemas.net/movies/5505.html?t=futakotamagawa",
      "status": "soon",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5538",
      "t": "開戦前夜",
      "date": "2026-07-31",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMjRfMDlfNTcwXzIxNzkxNF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/217914_screenShots.jpg",
      "actor": "池松壮亮／仲野太賀／岩田剛典／中村蒼／三浦貴大／二階堂ふみ／杉田雷麟／北村有起哉／嶋田久作／中野英雄／渡辺いっけい／別所哲也／松田龍平／奥田瑛二／國村隼／佐藤隆太／江口洋介／佐藤浩市 ほか",
      "director": "石井裕也",
      "env": "",
      "site": "https://109cinemas.net/movies/5538.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5545",
      "t": "ブルーロック",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDcvMTZfNDlfMDRfNzI1XzIyMTE4Nl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/221186_screenShots.jpg",
      "actor": "⾼橋⽂哉／櫻井海⾳／⾼橋恭平／野村康太／⻘⽊柚／⻄垣匠／橘優輝／⽯川雷蔵／岩永丞威／浅野竣哉／櫻井佑樹／倉悠貴／東啓介／綱啓永／窪⽥正孝／K(＆TEAM)／樋口幸平／畑芽育／富本惣昭／木田佳介／三浦獠太／平山裕介／山時聡真／野間口徹／野波麻帆／春海四方 ほか",
      "director": "瀧悠輔",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5545.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5546",
      "t": "ミニオンズ＆モンスターズ",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDEvMTBfNDJfMjNfOF8yMjM3MTFfc2NyZWVuU2hvdHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/223711_screenShots.jpg",
      "actor": "【日本語吹き替え版】松平健／千葉雄大／鈴木愛理／山寺宏一／バッテリィズ(エース／寺家)／LiSA／銀河万丈／寺依沙織／小野友樹／芹澤優 ほか",
      "director": "ピエール・コフィン",
      "env": "4DX,SCREENX,ULTRA-4DX",
      "site": "https://109cinemas.net/movies/5546.html?t=futakotamagawa",
      "status": "soon",
      "cat": "fam",
      "age": "全年齢（幼児〜大人）",
      "kidScore": 8
    },
    {
      "id": "5547",
      "t": "あの星が降る丘で、君とまた出会いたい。",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMjMvMDlfMTlfMDhfMjY4XzIwNjU1OV9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/206559_screenShots.jpg",
      "actor": "福原遥／細田佳央太／出口夏希／豊嶋花／井之脇海／伊藤健太郎／中嶋朋子／水上恒司／上川周作／小野塚勇人／松坂慶子／倍賞千恵子 ほか",
      "director": "新城 毅彦",
      "env": "",
      "site": "https://109cinemas.net/movies/5547.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5556",
      "t": "NEWシネマ歌舞伎『四谷怪談』",
      "date": "2026-08-07",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDEvMTFfMTFfNDNfNzU2XzU1MDI4X3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/55028_screenShots.jpg",
      "actor": "中村獅童／中村勘九郎／中村七之助／中村扇雀／片岡亀蔵／中村国生／中村鶴松／真那胡敬二／大森博史／首藤康之／笹野高史　ほか",
      "director": "串田和美",
      "env": "",
      "site": "https://109cinemas.net/movies/5556.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5633",
      "t": "劇場版　魔法少女まどか☆マギカ　［新編］ 叛逆の物語",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDIvMTBfNTFfMzlfMzY4XzE0MzI2X3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/14326_thumbnails.jpg",
      "actor": "【声の出演】悠木碧／斎藤千和／水橋かおり／喜多村英梨／野中藍／加藤英美里／阿澄佳奈 ほか",
      "director": "宮本幸裕",
      "env": "",
      "site": "https://109cinemas.net/movies/5633.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5548",
      "t": "オークストリートの異変",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTAvMjFfMDBfMTNfNTgxXzIyNDA3NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224074_screenShots.jpg",
      "actor": "ユアン・マクレガー／アン・ハサウェイ／メイジー・ステラ／クリスチャン・コンヴェリー【日本語吹き替え】森川智之／坂本真綾／早見沙織／木村皐誠 ほか",
      "director": "デヴィッド・ロバート・ミッチェル",
      "env": "IMAX,4DX,SCREENX",
      "site": "https://109cinemas.net/movies/5548.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5579",
      "t": "レディ・オア・ノット 2",
      "date": "2026-08-14",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDkvMTVfNDlfNTlfMzk1XzIyNzEyOF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227128_screenShots.jpg",
      "actor": "サマラ・ウィーヴィング／キャスリン・ニュートン／サラ・ミシェル・ゲラー／デヴィッド・クローネンバーグ／イライジャ・ウッド ほか",
      "director": "マット・ベティネッリ＝オルピン／タイラー・ジレット(レディオ・サイレンス)",
      "env": "",
      "site": "https://109cinemas.net/movies/5579.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5550",
      "t": "劇場版『TOKYO MER～走る緊急救命室〜CAPITAL CRISIS』",
      "date": "2026-08-21",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTVfMThfMDFfMzZfMjE4MDM5X3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/218039_screenShots.jpg",
      "actor": "鈴木亮平／賀来賢人／赤楚衛二／桜田ひより／津田健次郎／ファーストサマーウイカ／岩瀬洋志／菜々緒／杏／古川雄大／渡辺真起子／鶴見辰吾／要潤／仲里依紗／石田ゆり子／橋本さとし／江口洋介／高杉真宙／生見愛瑠／宮澤エマ／小手伸也／フォンチー／伊藤淳史 ほか",
      "director": "松木彩",
      "env": "IMAX",
      "site": "https://109cinemas.net/movies/5550.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5583",
      "t": "新感染 ファイナル・エクスプレス 4K",
      "date": "2026-08-21",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTIvMTVfNDNfNTZfMzY0XzIyNzEzMl9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227132_screenShots.jpg",
      "actor": "コン・ユ／マ・ドンソク／チョン・ユミ／キム・スアン／チェ・ウシク／シム・ウンギョン ほか",
      "director": "ヨン・サンホ",
      "env": "",
      "site": "https://109cinemas.net/movies/5583.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5587",
      "t": "ドラマなふたり",
      "date": "2026-08-21",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMTgvMTFfMDZfNDNfOThfMjI1Mjc2X3NjcmVlblNob3RzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/225276_screenShots.jpg",
      "actor": "ゼンデイヤ／ロバート・パティンソン／アラナ・ハイム／ママドゥ・アティエ／ヘイリー・ゲイツ／ゾーイ・ウィンターズ／シドニー・レモン／マイケル・アボット・Jr ほか",
      "director": "クリストファー・ボルグリ",
      "env": "",
      "site": "https://109cinemas.net/movies/5587.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5635",
      "t": "シェルター",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDIvMTZfMTZfNTJfOTk5XzIyNzgwOF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/227808_screenShots.jpg",
      "actor": "ジェイソン・ステイサム／ボディ・レイ・ブレスナック／ビル・ナイ／ナオミ・アッキー／ハリエット・ウォルター／ダニエル・メイズ ほか",
      "director": "リック・ローマン・ウォー",
      "env": "",
      "site": "https://109cinemas.net/movies/5635.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5647",
      "t": "劇場版 TUBE 40th Anniversary Live ＆ Documentary ～40周年の航海記～",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDkvMTFfNDBfNDRfMjA0XzIzMDQ2NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/230464_screenShots.jpg",
      "actor": "TUBE(前田亘輝／春畑道哉／角野秀行／松本玲二)",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5647.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5554",
      "t": "劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDYvMDEvMTFfMDNfMDdfOTk0XzE2MTY5NF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/161694_screenShots.jpg",
      "actor": "【声の出演】悠木碧／斎藤千和／水橋かおり／喜多村英梨／野中藍／阿澄佳奈／加藤英美里 ほか",
      "director": "宮本幸裕",
      "env": "",
      "site": "https://109cinemas.net/movies/5554.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5561",
      "t": "私はあなたを知らない、",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTZfNTdfNDNfODUxXzIyMDQ2N19zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/220467_screenShots.jpg",
      "actor": "坂口健太郎／早瀬憩／倉田瑛茉／稲垣来泉／和田光沙／片山友希／畦田ひとみ／田牧そら／渡辺真起子／足立智充／黑田大輔／滝藤賢一／原田美枝子 ほか",
      "director": "中野量太",
      "env": "",
      "site": "https://109cinemas.net/movies/5561.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5566",
      "t": "時には懺悔を",
      "date": "2026-08-28",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTZfNTlfMTFfNzg1XzE4NzgyNF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/187824_screenShots.jpg",
      "actor": "西島秀俊／満島ひかり／黒木華／宮藤官九郎／毎熊克哉／鈴木仁／烏森まど／山崎七海／唯野未歩子／野呂佳代／長井短／しんすけ／山下舜太／諸角優空／柴咲コウ／塚本晋也／片岡鶴太郎／佐藤二朗／役所広司 ほか",
      "director": "中島哲也",
      "env": "",
      "site": "https://109cinemas.net/movies/5566.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5626",
      "t": "べべフィン・ザ・ムービー：うたとまほうのピンキッツワールド",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMzFfNDlfNjExXzIyNTUwMF9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/225500_screenShots.jpg",
      "actor": "",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5626.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5627",
      "t": "獣兵衛忍風帖",
      "date": "2026-09-04",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTUvMTdfMTRfMDlfOTU1X2p5dWJlX3Bvc3Rlcl80Sy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/jyube_poster_4K.jpg",
      "actor": "山寺宏一／篠原恵美／青野武／郷里大輔／関俊彦／森山周一郎",
      "director": "川尻善昭",
      "env": "",
      "site": "https://109cinemas.net/movies/5627.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5616",
      "t": "ルックバック",
      "date": "2026-09-11",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMDVfNTdfNzMzXzIxODA0MF90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/218040_thumbnails.jpg",
      "actor": "出口夏希／蒔田彩珠／七瀬ふうり／岡田六花／菅田将暉／野呂佳代／宮藤官九郎／山田真歩／池田良／佐々木みゆ ほか",
      "director": "是枝裕和",
      "env": "",
      "site": "https://109cinemas.net/movies/5616.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5657",
      "t": "ワンオペレーション",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTQvMDlfNDNfMTFfMTk0XzIzMTEzN190aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/231137_thumbnails.jpg",
      "actor": "ローズ・バーン／コナン・オブライエン／エイサップ・ロッキー／ダニエル・マクドナルド ほか",
      "director": "メアリー・ブロンスタイン",
      "env": "",
      "site": "https://109cinemas.net/movies/5657.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5619",
      "t": "踊る大捜査線 N.E.W. メトロポリスを駆け抜けろ！",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMDhfMTRfMzNfMTg2MzU3X3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/186357_thumbnails.jpg",
      "actor": "織田裕二／趣里／白洲迅／佐々木蔵之介／増田貴久／野呂佳代／玉井詩織(ももいろクローバーZ)／藤吉夏鈴(櫻坂 46)／齊藤なぎさ／佐藤二朗 ほか",
      "director": "本広克行  ",
      "env": "",
      "site": "https://109cinemas.net/movies/5619.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5620",
      "t": "映画名探偵プリキュア！不思議な庭と2人の秘密",
      "date": "2026-09-18",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMDlfNTBfMTg5XzIyNDU2Ml9zY3JlZW5TaG90cy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/224562_screenShots.jpg",
      "actor": "【声の出演】千賀光莉／本渡楓／東山奈央／松岡美⾥／髙橋ミナミ／⾼森奈津美／南條愛乃／花井美春／⻑縄まりあ／種﨑敦美／松⽥颯⽔／上⽥麗奈／加藤英美⾥／⽺宮妃那／梶裕貴 ほか",
      "director": "上⽥華⼦",
      "env": "",
      "site": "https://109cinemas.net/movies/5620.html?t=futakotamagawa",
      "status": "soon",
      "cat": "kid",
      "age": "幼児〜小学生",
      "kidScore": 10
    },
    {
      "id": "5643",
      "t": "マッチング TRUE LOVE",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMTQvMDlfNDdfMzhfNzQ3XzIxNjYxMV90aHVtYm5haWxzLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/216611_thumbnails.jpg",
      "actor": "土屋太鳳／佐久間大介(Snow Man)／クァク・ドンヨン／豊嶋花／倉悠貴／根矢涼香／冨手麻妙／塚田僚一／瀧七海／濱正悟／加藤史帆／花瀬琴音／伊島空／後藤剛範／真飛聖 ほか",
      "director": "内田英治",
      "env": "",
      "site": "https://109cinemas.net/movies/5643.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    },
    {
      "id": "5624",
      "t": "シネマ歌舞伎　ふるあめりかに袖はぬらさじ",
      "date": "2026-09-25",
      "img": "https://109cinemas.net/media/W1siZiIsIjIwMjYvMDcvMDEvMTVfMjdfMjNfNzI5XzE3NzczX3RodW1ibmFpbHMuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/17773_thumbnails.jpg",
      "actor": "坂東玉三郎／中村獅童／中村七之助／中村福助／市川海老蔵／坂東三津五郎／中村勘三郎　ほか",
      "director": "",
      "env": "",
      "site": "https://109cinemas.net/movies/5624.html?t=futakotamagawa",
      "status": "soon",
      "cat": "gen",
      "age": "中学生〜大人",
      "kidScore": 2
    }
  ]
};
